version: "3.7"

services:

  # Konfigurasi untuk service item-app:
  item-app:
    # Menggunakan image ahdan86/item-app:v1
    image: ahdan86/item-app:v1
    # Command yang dijalankan untuk service item-app
    command: sh -c "npm install --production --unsafe-perm && npm run build && npm run start"
    # Map port 8080 container ke port 80 host
    ports: 
      - 80:8080
    # Environment untuk service item-app
    environment:
      DB_HOST: item-db
      NODE_ENV: production
    # Expose port 8080 pada container
    expose:
      - 8080
    # Restart Policy untuk service item-app
    restart: on-failure
    # Dependes on service item-db berjalan terlebih dahulu untuk service item-app
    depends_on:
      item-db:
        condition: service_completed_successfully

  # Konfigurasi untuk service item-db:
  item-db:
    # Menggunakan image mongo:3
    image: mongo:3
    # Restart Policy untuk service item-db
    restart: on-failure
    # Volume untuk service item-db
    volumes:
      - app-db:/var/lib/mongodb
    
volumes:
  app-db: 
