name: CI Pipeline 
on:
  push:
    branches:
      - karsajobs-ui

jobs:
  pipeline:
    name: CI Pipeline UI
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Hadolint
        uses: hadolint/hadolint-action@v3.1.0
        with:
          dockerfile: Dockerfile
      
      - name: Export docker password and login
        run: |
          export PASSWORD_DOCKER_HUB=${{ secrets.DOCKER_PASSWORD }}
          chmod +x build_push_images_karsajobs_ui.sh
          ./build_push_images_karsajobs_ui.sh