name: CI Pipeline 
on:
  push:
    branches:
      - karsajobs

jobs:
  pipeline:
    name: CI Pipeline
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Hadolint
        uses: hadolint/hadolint-action@v3.1.0
        with:
          dockerfile: Dockerfile
      
      - name: Run Unit test on golang app
        run: go test -v -short --count=1 $(go list ./...)
      
      - name: Export docker password and login
        run: | 
          export PASSWORD_DOCKER_HUB=${{ secrets.DOCKER_PASSWORD }}
          chmod +x build_push_image_karsajobs.sh
          ./build_push_image_karsajobs.sh
          